# JOIN_REQUEST = 0
# JOIN_ACCEPT  = 1
# UNCONFIRMED_DATA_UP = 2
# UNCONFIRMED_DATA_DOWN = 3
# CONFIRMED_DATA_UP = 4
# CONFIRMED_DATA_DOWN = 5
# RFU = 6

stringMessageType = ['JOIN_REQUEST', 'JOIN_ACCEPT', 'UNCONFIRMED_DATA_UP', 'UNCONFIRMED_DATA_DOWN', 'CONFIRMED_DATA_UP', 'CONFIRMED_DATA_DOWN', 'RFU']